// <auto-generated />
using System;
using LibraryLocationQuerySystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryLocationQuerySystem.Migrations
{
    [DbContext(typeof(StoreManagerDbContext))]
    partial class StoreManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryLocationQuerySystem.Models.Book", b =>
                {
                    b.Property<string>("SortCallNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)");

                    b.Property<string>("FormCallNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PublicDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublishingHouse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("SortCallNumber", "FormCallNumber");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("LibraryLocationQuerySystem.Models.Location", b =>
                {
                    b.Property<byte>("LocationLevel")
                        .HasColumnType("tinyint");

                    b.Property<byte>("LocationId")
                        .HasColumnType("tinyint");

                    b.Property<byte>("LocationParent")
                        .HasColumnType("tinyint");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("LocationLevel", "LocationId", "LocationParent");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("LibraryLocationQuerySystem.Models.Store", b =>
                {
                    b.Property<string>("BooksSortCallNumber")
                        .HasColumnType("nchar(15)");

                    b.Property<string>("BooksFormCallNumber")
                        .HasColumnType("nchar(15)");

                    b.Property<byte>("LocationsLocationLevel")
                        .HasColumnType("tinyint");

                    b.Property<byte>("LocationsLocationId")
                        .HasColumnType("tinyint");

                    b.Property<byte>("LocationsLocationParent")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RemainNum")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("StoreDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("StoreNum")
                        .HasColumnType("tinyint");

                    b.HasKey("BooksSortCallNumber", "BooksFormCallNumber", "LocationsLocationLevel", "LocationsLocationId", "LocationsLocationParent");

                    b.HasIndex("LocationsLocationLevel", "LocationsLocationId", "LocationsLocationParent");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("LibraryLocationQuerySystem.Models.Store", b =>
                {
                    b.HasOne("LibraryLocationQuerySystem.Models.Book", null)
                        .WithMany("Stores")
                        .HasForeignKey("BooksSortCallNumber", "BooksFormCallNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryLocationQuerySystem.Models.Location", null)
                        .WithMany("Stores")
                        .HasForeignKey("LocationsLocationLevel", "LocationsLocationId", "LocationsLocationParent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryLocationQuerySystem.Models.Book", b =>
                {
                    b.Navigation("Stores");
                });

            modelBuilder.Entity("LibraryLocationQuerySystem.Models.Location", b =>
                {
                    b.Navigation("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
